name: Fee - 2 - Generate Withdraw Payload

on:
    workflow_dispatch:
        inputs:
            recipient:
                description: 'The wallet the fees should be sent to, defaults to the revenue multisig'
                require: false

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GRAPH_KEY: ${{ secrets.GRAPH_KEY }}

jobs:
    generatePayload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Generate Withdraw Payload
              env:
                  RECIPIENT: ${{ github.event.inputs.recipient }}
              run: bun ts-node ./src/feeAutomation/generateWithdrawPayload.ts

            - name: Create PR
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: 'Calculate distribution'
                  title: 'New fee withdraw payload'
                  assignees: franzns
                  branch: withdraw-payload
                  delete-branch: true
                  labels: 'Automated PR'
