name: Fee - 1 - Collect Fees from pools to controller

on:
    schedule:
        - cron: '0 0 * * *' # Runs at midnight every day
    workflow_dispatch:

env:
    UPDATER_WALLET: ${{ secrets.UPDATER_WALLET }}

jobs:
    collectFees:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Collect fees from v3 pools
              run: bun ts-node ./src/feeAutomation/collectFees.ts
