name: Trevee - Generate Bounty Payload

on:
    workflow_dispatch:
        inputs:
            amountUsd:
                description: 'The scUSD amount for the bounty (excl. fees)'
                require: true
            minRewardPerVoteUsd:
                description: 'Minimum reward per vote for veUSD'
                require: true
            maxRewardPerVoteUsd:
                description: 'Maximum reward per vote for veUSD'
                require: true
            amountEth:
                description: 'The scETH amount for the bounty (excl. fees)'
                require: true
            minRewardPerVoteEth:
                description: 'Minimum reward per vote for veETH'
                require: true
            maxRewardPerVoteEth:
                description: 'Maximum reward per vote for veETH'
                require: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    treveeBounty:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Generate Payload For Trevee Bounty
              env:
                  AMOUNT_USD: ${{ github.event.inputs.amountUsd }}
                  MIN_REWARD_PER_VOTE_USD: ${{ github.event.inputs.minRewardPerVoteUsd }}
                  MAX_REWARD_PER_VOTE_USD: ${{ github.event.inputs.maxRewardPerVoteUsd }}
                  AMOUNT_ETH: ${{ github.event.inputs.amountEth }}
                  MIN_REWARD_PER_VOTE_ETH: ${{ github.event.inputs.minRewardPerVoteEth }}
                  MAX_REWARD_PER_VOTE_ETH: ${{ github.event.inputs.maxRewardPerVoteEth }}

              run: bun ts-node ./src/treveeBounty/generateBountyPayload.ts

            - name: Create PR
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: 'Bounty Payload for Trevee'
                  title: 'New Trevee bounty for ${{ github.event.inputs.market }} with ${{ github.event.inputs.amount }}'
                  assignees: Ardordocc
                  branch: init-trevee-bounty-${{ github.event.inputs.market }}
                  delete-branch: true
                  labels: 'Automated PR'
