name: On Merge - Generate payload for a week of rewards

on:
    pull_request:
        types:
            - closed
        branches:
            - 'reward-payload/**'

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PROPOSER_WALLET: ${{ secrets.PROPOSER_WALLET }}

jobs:
    propose_reward_txns:
        # if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Generate msig txns
              env:
                  PROPOSER_WALLET: ${{ secrets.PROPOSER_WALLET }}
              run: bun ts-node ./src/gaugeAutomation/proposeRewardTransactionsFromCsv.ts
