name: Voting - 3 - Generate payload for Hiddenhand Beets bribes

on:
    workflow_dispatch:
        inputs:
            vote_end_timestamp:
                description: 'The timestamp of the end of the vote'
                require: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
    GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

jobs:
    generateHHPayload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Generate HH payload
              env:
                  GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
                  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
                  VOTE_END_TIMESTAMP: ${{ github.event.inputs.vote_end_timestamp }}
              run: bun ts-node ./src/gaugeAutomation/generateBribePayload.ts

            - name: Create PR
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: 'Inititalize new gauge epoch'
                  title: 'Hiddenhand payload for round ${{ github.event.inputs.vote_end_timestamp }}'
                  assignees: Ardordocc
                  branch: hh-payload
                  delete-branch: true
                  labels: 'Automated PR'
