name: ZZZ - On Merge - Propose weekly Reward Transactions

on:
    workflow_dispatch:
    pull_request:
        types:
            - closed

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PROPOSER_WALLET: ${{ secrets.PROPOSER_WALLET }}

jobs:
    proposeRewardTxns:
        if: github.event.pull_request.merged == true && ${{ github.event.label.name == 'weekly-rewards' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Generate msig txns
              env:
                  PROPOSER_WALLET: ${{ secrets.PROPOSER_WALLET }}
              run: bun ts-node ./src/gaugeAutomation/proposeRewardTransactions.ts
